files:
  - source: /LibreDirectClient/Base.lproj/Localizable.strings
    translation: /LibreDirectClient/%osx_locale%.lproj/Localizable.strings
  - source: /LibreDirectClientUI/Base.lproj/Localizable.strings
    translation: /LibreDirectClientUI/%osx_locale%.lproj/Localizable.strings
